replicaCount: 2

environment: prod

image:
  repository: shivrajpatil1998/app3
  tag: latest

service:
  type: NodePort
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
