trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'shivrajpatil1998/app2'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Docker Build and Push
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'Dockerserviceconnection'
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: 'app2/Dockerfile'
        tags: |
          latest

- stage: Deploy
  displayName: Deploy to Kubernetes
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy to AKS
    steps:
    - checkout: self

    - task: Kubernetes@1
      displayName: 'Initialize kubectl context'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'k8sservice-connection'
        command: get
        arguments: 'nodes'

    - task: Kubernetes@1
      displayName: 'Apply Deployment YAML'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'k8sservice-connection'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/app2/k8s/deploy-app2.yaml'

    - task: Kubernetes@1
      displayName: 'Apply Service YAML'
      inputs:
        connectionType: 'Kubernetes Service Connection'
        kubernetesServiceEndpoint: 'k8sservice-connection'
        command: apply
        useConfigurationFile: true
        configuration: '$(System.DefaultWorkingDirectory)/app2/k8s/service-app2.yaml'

