trigger:
  branches:
    include:
      - none

variables:
  imageName: 'shivrajpatil1998/app3'
  environment: 'blue'  # or 'green'

stages:
# ----------- Build Stage ------------
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: DockerBuild
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: 'Dockerserviceconnection'
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: 'app3/Dockerfile'
        tags: |
          latest

# ----------- Deploy Stage ------------
- stage: Deploy
  displayName: Helm Blue-Green Deploy to AKS
  dependsOn: Build
  jobs:
  - deployment: DeployApp
    displayName: Deploy via Helm
    environment: blue
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self  

          - task: HelmDeploy@1
            displayName: Helm Upgrade
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'k8sservice-connection'
              namespace: 'app3'
              command: 'upgrade'
              chartType: 'FilePath'
              chartPath: 'app3/helm/app3' 
              releaseName: 'app3-$(environment)'
              overrideValues: |
                image.repository=$(imageName)
                image.tag=latest
                environment=$(environment)
                service.type=NodePort

